command: [
  "uvicorn",
  "server.app:app"
]

# User Authorization Configuration
# These scopes define what the app can access on behalf of users
# See: https://docs.databricks.com/dev-tools/databricks-apps/auth.html
user_authorization:
  scopes:
    # SQL and Data Access
    - sql                                    # Execute SQL and manage SQL related resources
    - catalog.catalogs:read                  # Read catalogs in Unity Catalog
    - catalog.schemas:read                   # Read schemas in Unity Catalog
    - catalog.tables:read                    # Read tables in Unity Catalog
    - catalog.connections                    # Manage connections to external services and Lakehouse Federation
    
    # Model Serving and Vector Search
    - serving.serving-endpoints              # Manage model serving endpoints
    - vectorsearch.vector-search-indexes     # Manage vector search indexes
    
    # Dashboards and Files
    - dashboards.genie                       # Manage Genie spaces
    - files.files                            # Manage files and directories
    
    # IAM (Default scopes - required)
    - iam.access-control:read                # Read access control settings and permissions (default)
    - iam.current-user:read                  # Read authenticated user's basic information (default)

env:
  # Databricks SDK Configuration (OAuth authentication is automatic)
  # Unity Catalog Configuration
  - name: DATABRICKS_WAREHOUSE_ID
    value: "5df2ea9402e3c33b"
  - name: DATABRICKS_CATALOG
    value: "main"
  - name: DATABRICKS_SCHEMA
    value: "samples"
  
  # Lakebase Configuration (OAuth authentication is automatic)
  - name: LAKEBASE_HOST
    value: "instance-0fac1568-f318-4b0d-9110-cd868b343908.database.cloud.databricks.com"
  - name: LAKEBASE_PORT
    value: "5432"
  - name: LAKEBASE_DATABASE
    value: "app_database"
  

  
  # Observability Configuration
  - name: LOG_LEVEL
    value: "INFO"
  - name: LOG_FORMAT
    value: "json"
